### ISSUE TITLE
keywording as stable is undesirable for most users

### ISSUE THREAD

**Issue by Foyaxe** [killer2tester/gentoo-overlay-lif#1]
many users only want to get single packages from an overlay and still add the complete overlay to layman in order to receive updates to these packages automatically.
So it is better practise to add these single packages to package.keywords so that other packages are not overruled by the overlay. Therefore the overlay should have all packages keyworded as testing.
Otherwise, users have to mask your overlay like this: package.mask
*/*::lif

**Comment by killer2tester** [comment]
On Tue, 2015-07-07 at 06:31 -0700, Foyaxe wrote:
> many users only want to get single packages from an overlay and still
> add the complete overlay to layman in order to receive updates to
> these packages automatically.
> So it is better practise to add these single packages to
> package.keywords so that other packages are not overruled by the
> overlay. Therefore the overlay should have all packages keyworded as
> testing.
> Otherwise, users have to mask your overlay like this: package.mask
> /::lif
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 
Oh, ok i fix. Thx for info.
