### ISSUE TITLE
Problems with the variable $CARCH.

### ISSUE THREAD

**Issue by andrex4k** [killer2tester/gentoo-overlay-lif#3]
Of course it can be and should be. Or is it just me)

cat: /var/lib/layman/lif/sys-kernel/linux/files/4.5/config.: No such file or directory
* The specific snippet of code:
 *           cat "${FILESDIR}/${KAPIVER}/config.${CARCH}" > "${S}/.config" || die;

Can add in ebuild or as that through USE flags. CARCH=$(arch) ?

**Comment by killer2tester** [comment]
You build for x86, x86_64 architecture or arm, powerpc, etc?

**Comment by andrex4k** [comment]
for x86, x86_64, thx.

**Comment by killer2tester** [comment]
Fixed.
